;Write an assembly language program to count the number of 1's in a 16 bit number

LXI H,3000H ;
MOV A,M ;FIRST 8 BIT STORE IN A
CALL COUNT_BITS ;CALL COUNT_BITS SUBROUTINE 
MOV B,A ;TEMPORARY STORE THE VALUE OF A WHICH IS RETURNED FROM SUBROUTINE
INX H 
CALL COUNT_BITS ; CALL FOR NEXT 8 BITS NUMBER
ADD B ;ADD TWO COUNTERS VALUE
STA 3003H ;STORE OUTPUT 
HLT

COUNT_BITS: MVI C,00H ;INITIAL STORE, COUNT=0
	MVI D,08H ;FOR 8 BITS, SOTRE IN D
COUNT_LOOP: RRC ;ROTATE ACCUMULATOR RIGHT THROUGH CARRY
	JNC INCREMENT_SKIP ;IF CARRY=0 THEN SKIP INCREMENT
	INR C ;IF CARRY=1 THEN INCREMENT THE VALUE OF COUNTER
INCREMENT_SKIP: DCR D ;DECREMENT THE BITS 
	JNZ COUNT_LOOP ;LOOP IS GOING UNTIL BITS ARE 0
MOV A,C 
RET ;RETURN